package org.frozenarc.zeframework.viewloader;

import java.io.ByteArrayInputStream;
import java.io.OutputStream;
import org.frozenarc.zeframework.connector.ActionViewConnector;
import org.frozenarc.zeframework.constants.FWConstants;
import org.frozenarc.zeframework.evententities.EventEntities;
import org.frozenarc.zeframework.model.FileData;
import org.frozenarc.zeframework.model.Model;

/**
 * The class is used internally by framework to download file when user clicks a link generated by 'filedownload' tag.
 * @author Manan
 */
public class FileDownloader implements ViewLoader {

    public void loadView(Model[] models, ActionViewConnector connector, EventEntities entities) throws Exception {
        String fileId = entities.getRequest().getParameter(FWConstants.FILE_ID);
        FileData fileData = (FileData) entities.getRequest().getSession().getAttribute(FWConstants.FILEDATA_ID + fileId);
        if (fileData == null) {
            fileData = (FileData) entities.getRequest().getServletContext().getAttribute(FWConstants.FILEDATA_ID + fileId);
        }
        if (fileData != null) {
            entities.getResponse().setContentType(fileData.getDownloadContentType());
            entities.getResponse().setHeader("Content-Disposition", fileData.getContentDispositionType() + "; filename=\"" + fileData.getFileName() + "\"");
            entities.getResponse().getOutputStream().write(fileData.getData());
            ByteArrayInputStream inputStream=new ByteArrayInputStream(fileData.getData());
            OutputStream outputStream=entities.getResponse().getOutputStream();
            int length;
            byte[] chunk = new byte[400];
            while ((length = inputStream.read(chunk)) > 0) {
                outputStream.write(chunk, 0, length);
            }
        } else {
            entities.getResponse().getOutputStream().write(new byte[0]);
        }
        entities.getResponse().getOutputStream().flush();
    }
}
